#!/usr/bin/env python
"""
dump datasets from a given CKAN organization as json lines

Usage:
  orgdatasets ORG_NAME [-r SITE_URL] [-a APIKEY]
  orgdatasets -h
  orgdatasets --version

Options:
  -h                    show this screen
  --version             show version
  -a --apikey           API key to use for remote actions
  -r --remote=SITE_URL  URL of CKAN server
                        [default: http://ndmckand1.statcan.ca/zj]
"""

__version__ = '0.1'

from docopt import docopt
import ckanapi
import json

REQUEST_ROWS = 1000

def main():
    arguments = docopt(__doc__, version=__version__)
    ckan = ckanapi.RemoteCKAN(arguments['--remote'],
        apikey=arguments['--apikey'],
        user_agent="orgdatasets/{version}".format(version=__version__))

    org = ckan.action.organization_show(
        id=arguments['ORG_NAME'],
        include_datasets=False)
    offset = 0

    while True:
        result = ckan.action.package_search(
            fq='owner_org:"{0}"'.format(org['id']),
            facet='false',
            start=offset,
            rows=REQUEST_ROWS)
        datasets = result['results']

        if not datasets:
            break
        for d in datasets:
            print json.dumps(d)
        offset += len(datasets)

main()
